
import type { Event, Category } from './types';

const categoryImageMap: Record<string, string> = {
  'afterwork': 'http://bilingue31.free.fr/annonce_Afterwork_1_OK.jpg',
  'atelier artistique': 'http://bilingue31.free.fr/annonce_AtelierArt_OK.jpg',
  'balade dans la nature': 'http://bilingue31.free.fr/annonce_Balade_Nature_OK.jpg',
  'bar, pub': 'http://bilingue31.free.fr/annonce_bar_OK.jpg',
  'Bien-Être': 'http://bilingue31.free.fr/annonce_BienEtre_OK.jpg',
  'billard': 'http://bilingue31.free.fr/annonce_Billard_OK.jpg',
  'Blind Test': 'http://bilingue31.free.fr/annonce_BlindTest_OK.jpg',
  'botanique': 'http://bilingue31.free.fr/annonce_Botanique_OK.jpg',
  'bowling': 'http://bilingue31.free.fr/annonce_Bowling_OK.jpg',
  'brunch': 'http://bilingue31.free.fr/annonce_Brunch_OK.jpg',
  'chant': 'http://bilingue31.free.fr/annonce_Chant_OK.jpg',
  'cinéma': 'http://bilingue31.free.fr/annonce_Cinema_1_OK.jpg',
  'concert': 'http://bilingue31.free.fr/annonce_concert_1_OK.jpg',
  'conférence': 'http://bilingue31.free.fr/annonce_conference_1_OK.jpg',
  'couture et crochet': 'http://bilingue31.free.fr/annonce_couture_1_OK.jpg',
  'cueillette': 'http://bilingue31.free.fr/annonce_ceuillette_OK.jpg',
  'cuisine': 'http://bilingue31.free.fr/annonce_cuisine_1_OK.jpg',
  'danse': 'http://bilingue31.free.fr/annonce_danse_OK.jpg',
  'débat': 'http://bilingue31.free.fr/annonce_debat_OK.jpg',
  'découverte du patrimoine': 'http://bilingue31.free.fr/annonce_decouvrepatri_OK.jpg',
  'dessin': 'http://bilingue31.free.fr/annonce_dessin_1_OK.jpg',
  'discothèque': 'http://bilingue31.free.fr/annonce_discotheque_1_OK.jpg',
  'écologie': 'http://bilingue31.free.fr/annonce_Ecologie_OK.jpg',
  'écriture': 'http://bilingue31.free.fr/annonce_ecriture_OK.jpg',
  'emploi': 'http://bilingue31.free.fr/annonce_Emploi_1_OK.jpg',
  'Escape Game': 'http://bilingue31.free.fr/annonce_EscapeGame_1_OK.jpg',
  'exposition': 'http://bilingue31.free.fr/annonce_Exposition_OK.jpg',
  'impro': 'http://bilingue31.free.fr/annonce_improvisation_OK.jpg',
  'informatique': 'http://bilingue31.free.fr/annonce_Informatique_OK.jpg',
  'jardinage': 'http://bilingue31.free.fr/annonce_Jardinage_OK.jpg',
  'jeux': 'http://bilingue31.free.fr/annonce_Jeux_1_OK.jpg',
  'karaoké': 'http://bilingue31.free.fr/annonce_Karaoke_OK.jpg',
  'langue': 'http://bilingue31.free.fr/annonce_Langues_1_OK.jpg',
  'Laser Game': 'http://bilingue31.free.fr/annonce_LaserGame_1_OK.jpg',
  'lecture': 'http://bilingue31.free.fr/annonce_Lecture_OK.jpg',
  'musées': 'http://bilingue31.free.fr/annonce_Musees_OK.jpg',
  'oenologie': 'http://bilingue31.free.fr/annonce_oenologie_1_OK.jpg',
  'peinture': 'http://bilingue31.free.fr/annonce_peinture_1_OK.jpg',
  'philo': 'http://bilingue31.free.fr/annonce_Philo_OK.jpg',
  'photographie': 'http://bilingue31.free.fr/annonce_Photo_1_OK.jpg',
  'pique-nique': 'http://bilingue31.free.fr/annonce_PiqueNique_4_OK.jpg',
  'psycho': 'http://bilingue31.free.fr/annonce_psycho_1_OK.jpg',
  'randonnée': 'http://bilingue31.free.fr/annonce_rando_1_OK.jpg',
  'restaurant': 'http://bilingue31.free.fr/annonce_restaurant_1_OK.jpg',
  'salon de thé': 'http://bilingue31.free.fr/annonce_salondeThe_OK.jpg',
  'sciences': 'http://bilingue31.free.fr/annonce_Sciences_OK.jpg',
  'shopping': 'http://bilingue31.free.fr/annonce_shopping_1_OK.jpg',
  'soirée entre filles': 'http://bilingue31.free.fr/annonce_soireefilles_OK.jpg',
  'social': 'http://bilingue31.free.fr/annonce_Social_OK.jpg',
  'sortie étudiante': 'http://bilingue31.free.fr/annonce_ERASMUS_OK.jpg',
  'sortie en Andorre': 'http://bilingue31.free.fr/annonce_Andorre_1_OK.jpg',
  'sortie en Espagne': 'http://bilingue31.free.fr/annonce_Espagne_1_OK.jpg',
  'spectacle': 'http://bilingue31.free.fr/annonce_Spectacle_OK.jpg',
  'spiritualité': 'http://bilingue31.free.fr/annonce_Spirirtualite_OK.jpg',
  'Stand Up': 'http://bilingue31.free.fr/annonce_StandUp_OK.jpg',
  'théâtre': 'http://bilingue31.free.fr/annonce_Theatre_OK.jpg',
  'train à 1 euro': 'http://bilingue31.free.fr/annonce_Train_OK.jpg',
  'vernissage et inauguration': 'http://bilingue31.free.fr/annonce_Vernissage_1_OK.jpg',
  'vidéo': 'http://bilingue31.free.fr/annonce_video_1_OK.jpg',
  'visite urbaine': 'http://bilingue31.free.fr/annonce_visiteville_OK.jpg',
  'volontariat': 'http://bilingue31.free.fr/annonce_Volontaires_1_OK.jpg',
  'voyage': 'http://bilingue31.free.fr/annonce_Voyage_OK.jpg',
  'autre sport': 'http://bilingue31.free.fr/annonce_autresport_OK.jpg',
  'camping': 'http://bilingue31.free.fr/annonce_Camping_OK.jpg',
  'fitness': 'http://bilingue31.free.fr/annonce_fitness_OK.jpg',
  'football': 'http://bilingue31.free.fr/annonce_football_OK.jpg',
  'jogging': 'http://bilingue31.free.fr/annonce_jogging_OK.jpg',
  'karting': 'http://bilingue31.free.fr/annonce_karting_OK.jpg',
  'natation': 'http://bilingue31.free.fr/annonce_nage_1_OK.jpg',
  'navigation': 'http://bilingue31.free.fr/navigation_OK.jpg',
  'patinoire': 'http://bilingue31.free.fr/annonce_patinoire_OK.jpg',
  'pétanque': 'http://bilingue31.free.fr/annonce_Petanque_OK.jpg',
  'plage': 'http://bilingue31.free.fr/annonce_Plage_OK.jpg',
  'rugby': 'http://bilingue31.free.fr/annonce_rugby_OK.jpg',
  'ski': 'http://bilingue31.free.fr/annonce_ski_OK.jpg',
  'sport de balle ou ballon': 'http://bilingue31.free.fr/annonce_sportballe_OK.jpg',
  'squash': 'http://bilingue31.free.fr/annonce_squash_OK.jpg',
  'tennis': 'http://bilingue31.free.fr/annonce_tennis_OK.jpg',
  'vélo': 'http://bilingue31.free.fr/annonce_velo_OK.jpg',
  'yoga': 'http://bilingue31.free.fr/annonce_yoga_OK.jpg'
};

const getDefaultImage = (category: Category) => {
    return categoryImageMap[category] || 'https://picsum.photos/seed/default/600/400';
};


export const categories: Category[] = [
  'afterwork',
  'atelier artistique',
  'balade dans la nature',
  'bar, pub',
  'Bien-Être',
  'billard',
  'Blind Test',
  'botanique',
  'bowling',
  'brunch',
  'chant',
  'cinéma',
  'concert',
  'conférence',
  'couture et crochet',
  'cueillette',
  'cuisine',
  'danse',
  'débat',
  'découverte du patrimoine',
  'dessin',
  'discothèque',
  'écologie',
  'écriture',
  'emploi',
  'Escape Game',
  'exposition',
  'impro',
  'informatique',
  'jardinage',
  'jeux',
  'karaoké',
  'langue',
  'Laser Game',
  'lecture',
  'musées',
  'oenologie',
  'peinture',
  'philo',
  'photographie',
  'pique-nique',
  'psycho',
  'randonnée',
  'restaurant',
  'salon de thé',
  'sciences',
  'shopping',
  'soirée entre filles',
  'social',
  'sortie étudiante',
  'sortie en Andorre',
  'sortie en Espagne',
  'spectacle',
  'spiritualité',
  'Stand Up',
  'théâtre',
  'train à 1 euro',
  'vernissage et inauguration',
  'vidéo',
  'visite urbaine',
  'volontariat',
  'voyage',
  'autre sport',
  'camping',
  'fitness',
  'football',
  'jogging',
  'karting',
  'natation',
  'navigation',
  'patinoire',
  'pétanque',
  'plage',
  'rugby',
  'ski',
  'sport de balle ou ballon',
  'squash',
  'tennis',
  'vélo',
  'yoga',
];

export const events: Event[] = [
  {
    id: '1',
    name: 'Concert de Jazz au BIKINI',
    category: 'concert',
    date: 'October 26, 2024 - 20:00',
    address: 'Le Bikini, Rue Théodore Monod, Ramonville-Saint-Agne',
    description: 'Une soirée inoubliable avec les plus grands noms du jazz contemporain.',
    longDescription: 'Plongez dans une atmosphère feutrée et laissez-vous emporter par les mélodies envoûtantes du jazz. Le Bikini, salle de concert emblématique de Toulouse, accueille un quartet de renommée internationale pour une performance unique. Une expérience à ne pas manquer pour tous les amateurs de musique live.',
    image: getDefaultImage('concert'),
    ticketsUrl: '#',
    isFavorite: false,
    location: { lat: 43.551, lng: 1.464 },
  },
  {
    id: '2',
    name: "Pièce 'Le Misanthrope' au TNT",
    category: 'théâtre',
    date: 'November 5, 2024 - 20:30',
    address: 'Théâtre de la Cité (TNT), 1 Rue Pierre Baudis, Toulouse',
    description: 'Redécouvrez le chef-d\'œuvre de Molière dans une mise en scène moderne et audacieuse.',
    longDescription: 'Le Théâtre de la Cité présente une nouvelle adaptation du "Misanthrope". Cette production met en lumière la pertinence intemporelle de la critique sociale de Molière, avec des costumes et un décor qui pontent le 17ème siècle et notre époque contemporaine.',
    image: getDefaultImage('théâtre'),
    ticketsUrl: '#',
    isFavorite: true,
    location: { lat: 43.606, lng: 1.444 },
  },
  {
    id: '3',
    name: 'Match de Rugby : Stade Toulousain',
    category: 'rugby',
    date: 'November 12, 2024 - 15:00',
    address: 'Stade Ernest-Wallon, 114 Rue des Troènes, Toulouse',
    description: 'Vibrez avec les Rouge et Noir pour un match de Top 14 explosif.',
    longDescription: 'Soutenez le Stade Toulousain dans son antre d\'Ernest-Wallon. Une ambiance électrique et un spectacle sportif de haut niveau sont garantis pour ce match crucial du championnat. Venez encourager les légendes du rugby toulousain.',
    image: getDefaultImage('rugby'),
    ticketsUrl: '#',
    isFavorite: false,
    location: { lat: 43.629, lng: 1.425 },
  },
  {
    id: '4',
    name: 'Exposition "Art & Cosmos"',
    category: 'exposition',
    date: 'Tout le mois de Novembre',
    address: 'Cité de l\'Espace, Avenue Jean Gonord, Toulouse',
    description: 'Une exploration fascinante des liens entre la création artistique et l\'exploration spatiale.',
    longDescription: 'La Cité de l\'Espace vous invite à un voyage unique où l\'art rencontre la science. L\'exposition "Art & Cosmos" présente des œuvres inspirées par l\'univers, des photographies prises par des télescopes spatiaux aux sculptures évoquant des nébuleuses lointaines.',
    image: getDefaultImage('exposition'),
    isFavorite: true,
    location: { lat: 43.587, lng: 1.492 },
  },
  {
    id: '5',
    name: 'Festival Gastronomique "Toulouse à Table"',
    category: 'restaurant',
    date: 'September 15-25, 2024',
    address: 'Place du Capitole, Toulouse',
    description: 'Dégustez les spécialités de la région avec les meilleurs chefs toulousains.',
    longDescription: 'Le festival "Toulouse à Table" transforme la Place du Capitole en un immense banquet à ciel ouvert. Des dizaines de stands proposent des dégustations, des ateliers de cuisine et des rencontres avec des producteurs locaux. Une célébration de la richesse culinaire du Sud-Ouest.',
    image: getDefaultImage('restaurant'),
    ticketsUrl: '#',
    isFavorite: false,
    location: { lat: 43.604, lng: 1.443 },
  },
  {
    id: '6',
    name: 'Cinéma en Plein Air au Jardin des Plantes',
    category: 'cinéma',
    date: 'Chaque Jeudi de l\'été',
    address: 'Jardin des Plantes, Allée Jules Guesde, Toulouse',
    description: 'Profitez des soirées d\'été avec une sélection de films classiques projetés en plein air.',
    longDescription: 'Apportez votre couverture et votre pique-nique pour une séance de cinéma magique sous les étoiles. Le cadre verdoyant du Jardin des Plantes offre une atmosphère unique pour (re)découvrir des films cultes sur grand écran, le tout gratuitement.',
    image: getDefaultImage('cinéma'),
    isFavorite: true,
    location: { lat: 43.593, lng: 1.449 },
  },
  {
    id: '7',
    name: 'Nuit des Chercheurs au Quai des Savoirs',
    category: 'sciences',
    date: 'September 27, 2024 - 18:00',
    address: 'Quai des Savoirs, 39 Allée Jules Guesde, Toulouse',
    description: 'Rencontrez les scientifiques qui façonnent le monde de demain.',
    longDescription: 'Une soirée exceptionnelle où la science devient accessible à tous. Participez à des expériences, assistez à des mini-conférences et discutez avec des chercheurs de toutes disciplines dans une ambiance conviviale et ludique.',
    image: getDefaultImage('sciences'),
    isFavorite: false,
    location: { lat: 43.592, lng: 1.449 },
  },
  {
    id: '8',
    name: 'Orchestre National du Capitole',
    category: 'concert',
    date: 'December 10, 2024 - 20:00',
    address: 'Halle aux Grains, 1 Place Dupuy, Toulouse',
    description: 'Un programme symphonique exceptionnel sous la direction d\'un chef de renommée mondiale.',
    longDescription: 'L\'Orchestre National du Capitole de Toulouse interprète des œuvres de Beethoven et Ravel dans l\'acoustique parfaite de la Halle aux Grains. Une soirée de musique classique d\'une intensité rare, portée par la virtuosité de ses musiciens.',
    image: getDefaultImage('concert'),
    ticketsUrl: '#',
    isFavorite: false,
    location: { lat: 43.601, lng: 1.454 },
  },
  {
    id: '9',
    name: 'Apéro Filles au Wallace',
    category: 'soirée entre filles',
    date: 'October 18, 2024 - 19:00',
    address: 'The Wallace, 16 Rue Saint-Rome, Toulouse',
    description: 'Retrouvons-nous pour un moment convivial entre filles.',
    longDescription: 'Une soirée pour papoter, rire et faire de nouvelles rencontres entre filles dans une ambiance décontractée. Que vous soyez nouvelle à Toulouse ou simplement désireuse d\'élargir votre cercle d\'amies, vous êtes la bienvenue.',
    image: getDefaultImage('soirée entre filles'),
    isFavorite: false,
    location: { lat: 43.602, lng: 1.443 },
  },
  {
    id: '10',
    name: 'Tarot Étudiant au Café Pop',
    category: 'sortie étudiante',
    date: 'October 21, 2024 - 20:00',
    address: 'Café Populaire, 9 Rue de la Colombette, Toulouse',
    description: 'Soirée jeux de cartes à tarif étudiant.',
    longDescription: 'Venez défier d\'autres étudiants au tarot ou à la belote dans un bar emblématique du quartier étudiant. Boissons à prix réduit sur présentation de la carte étudiante. Ambiance garantie !',
    image: getDefaultImage('sortie étudiante'),
    isFavorite: false,
    location: { lat: 43.605, lng: 1.453 },
  }
];
